### PR TITLE
Fix unit test, e2e test and lint issues.

### PR DESCRIPTION
**Pull request by narekcat**

### CODE REVIEW

**Comment by kylewu** [comment]
@Nachiappa thank you.

I try `npm run e2e` three times.

Twice i get this error
```
290 passing (42s)
  1 failing

  1) challenge API E2E tests
       search challenges API tests
         search challenges successfully 1:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/wwu/dev/copilot-dev/challenge-api/challenge-api/test/e2e/challenge.api.test.js)
```

Once I get error from the same test, but an equal error.
Would it be possible that this test case is not stable?

`npm run test` all pass. Great.

**Comment by narekcat** [comment]
@kylewu I'll check `npm run e2e` again.

**Comment by narekcat** [comment]
@kylewu - I have checked `npm run e2e` again, but didn't get an error. I have tried `npm run e2e` ten times sequentially and all passed. May be problem with you local deployment ? Try to drop and create tables, also initialize db and es.

**Comment by kylewu** [comment]
@narekcat thanks for testing it again.
I find the issue. config of mock-api needs to be updated as well, because mock-api is in docker-compose, DYNAMODB_URL should point to dynamodb:7777

**Pull request merged**
