### PR TITLE
Issue 91 fix: Update Postman collections

### PR DESCRIPTION
**Pull request by Gauravseta**

### CODE REVIEW

**Comment by kylewu** [comment]
@Gauravseta 

1. I get this error when running `create challenge by copilot`, any idea? 

```
{
    "message": "\"metadata\" position 1 contains a duplicate value"
}
```

2. Update challenge `update challenge 1 by admin` and others requests.
```
{
    "message": "\"termsIds\" is not allowed"
}
```

3. partial update challenge `partial update challenge 1 terms by admin`
```
{
    "message": "\"termsIds\" is not allowed"
}
```

**Comment by ThomasKranitsas** [comment]
1. That has been fixed in the latest code in `develop`
2 & 3. We no longer support `termIds`. We now have `terms` which is an array of UUIDs.

Please make sure the updated tests match with the Swagger as well as the code. Do not just update the POSTMAN collection without double-checking with the Swagger/Code.

**Comment by Gauravseta** [comment]
@ThomasKranitsas @kylewu I took latest develop branch locally.

1. Open postman and imported latest environment and collection file.
2. made challenge api run locally by making ES, dynambodb and mock-api up using docker-compose up
3. and then npm run start
4. and then in postman i made hit  create ChallengeType, create challenge phases, create timeline template, create challengetypetimeline templates, and then create challenge which works fine

I will try it all again

**Comment by Gauravseta** [comment]
@ThomasKranitsas @kylewu can I get AUTH tokens to check M2M requests? or is it not necessary to check those? also to check regarding attachementIds?

**Comment by ThomasKranitsas** [comment]
@rootelement ☝️

**Comment by rootelement** [comment]
Comment out the tests of attachmentIds. That work is in flight to change that. We'll run another task to update the attachments shortly.

Auth Tokens to test what exactly? Calling Projects/Terms? What are you going to test? Just reading from those related services?

**Comment by Gauravseta** [comment]
@rootelement Yes i will assume and skip some, but i was testing creating "challenge using m2m" and even partial update and update requests.
dont know If I am missing anything more

**Pull request merged**
