### PR TITLE
#116 fix unit tests

### PR DESCRIPTION
**Pull request by sjbr**
removed some test for no longer used properties (in schema) like:
 challenge.termsIds, forumId, track
also tests involving challengeSettings

### CODE REVIEW

**Comment by sjbr** [comment]
https://github.com/topcoder-platform/challenge-api/issues/116

**Comment by kylewu** [comment]
@sjbr thanks for the PR.
I just pull your code and run test, but i'm still seeing 38 failures.
Do all tests pass in your side?

**Comment by sjbr** [comment]
@kylewu 
Yes.

229 passing (16s)

**Comment by sjbr** [comment]
@kylewu 
Start mock-api (it doesn't start as part of docker-compose):
npm start

**Comment by kylewu** [comment]
@sjbr right. I see all pass now. Let me check the change

**Pull request merged**
